/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package component.managment.system;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Hardik Bhadru
 */
public class Change_Password extends javax.swing.JFrame {
    static String NAME = null,  roll = null,  Br = null,  Mail = null,num=null,pass=null,uni=null;
    /**
     * Creates new form Change_Password
     */
    public Change_Password() {
        initComponents();
        change1();
        setExtendedState(getExtendedState()|Login.MAXIMIZED_BOTH);
    }
    public void change(String name, String Rol, String br, String ml,String nu,String pas) {
        Change_Password.NAME = name;
        Change_Password.roll = Rol;
        Change_Password.Br = br;
        Change_Password.Mail = ml;
        Change_Password.num=nu;
        Change_Password.pass=pas;
    }
    void chan(String un){
        Change_Password.uni=un;
    }
    void change1() {
        jLabel4.setText(NAME);
        jLabel8.setText(roll);
        jLabel9.setText(Br);
        jLabel10.setText(Mail);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:-");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 120, 130, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(110, 120, 620, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Roll no:-");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 190, 130, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(130, 190, 600, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Branch:-");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 260, 140, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel9);
        jLabel9.setBounds(130, 260, 600, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email ID:-");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 330, 140, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel10);
        jLabel10.setBounds(150, 330, 680, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(90, 140, 830, 690);

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel11.setText("Re-Type NewPassword:-");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(110, 360, 280, 28);

        jPasswordField3.setBackground(new java.awt.Color(255, 255, 204));
        jPasswordField3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jPasswordField3);
        jPasswordField3.setBounds(110, 400, 410, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 204));
        jLabel12.setText("New Password:-");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(110, 210, 190, 28);

        jPasswordField2.setBackground(new java.awt.Color(255, 255, 204));
        jPasswordField2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jPasswordField2);
        jPasswordField2.setBounds(110, 250, 410, 40);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 204));
        jLabel13.setText("Old Password:-");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(110, 70, 190, 28);

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 204));
        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jPasswordField1);
        jPasswordField1.setBounds(110, 110, 410, 40);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(340, 520, 130, 40);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(150, 520, 140, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(1010, 140, 730, 690);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 52)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Change Password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(690, 40, 490, 60);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Created by:- Hardik Bhadru");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1610, 960, 300, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1950, 1230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String oldPwd=jPasswordField1.getText();
        String NewPwd=jPasswordField2.getText();
        String RePwd=jPasswordField3.getText();
        if(NewPwd.length()>=6){
        if(oldPwd.equals(NewPwd)){
            JOptionPane.showMessageDialog(this, "Your old password and new password are same. Please add new password.","error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        if(Br.equals("Diploma ICT")||Br.equals("Degree ICT")||Br.equals("ICT")){
         if(NewPwd.equals(RePwd)){
            if(oldPwd.equals(pass)){
                PreparedStatement ps=null;
                ResultSet rs=null;
                String query="UPDATE `ict_student` SET `Name`=?,`Roll_No`=?,`Mail_ID`=?,`Branch`=?,`Mobile_number`=?,`Password`=? WHERE `Password`='"+pass+"'";
                try{
                    ps=(PreparedStatement) MyConnection.getConnection().prepareStatement(query);
                    ps.setString(1, NAME);
                    ps.setString(2, roll);
                    ps.setString(3, Mail);
                    ps.setString(4, Br);
                    ps.setString(5, num);
                    ps.setString(6, NewPwd);
                     if(ps.executeUpdate()>0){
                            JOptionPane.showMessageDialog(this, "Password changes successfully.....");
                            if(HomePage.count==1){
                                new HomePage().setVisible(true);
                                this.setVisible(false);
                            }else{
                                new Admin_Login().setVisible(true);
                                this.setVisible(false);
                            }
                     }
                   
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Error!"+e);
                    jPasswordField1.setText("");
                    jPasswordField2.setText("");
                    jPasswordField3.setText("");
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Your old Password is not matched...Please try again");
                jPasswordField1.setText("");
                jPasswordField2.setText("");
                jPasswordField3.setText("");
            }
           
        }else{
            JOptionPane.showMessageDialog(this, "New Password Does not match...");
            jPasswordField1.setText("");
            jPasswordField2.setText("");
            jPasswordField3.setText("");
        }
    }else{
        if(NewPwd.equals(RePwd)){
            if(oldPwd.equals(pass)){
                PreparedStatement ps=null;
                String query="UPDATE `non_ict_student_registartion` SET `Name`=?,`Roll_No`=?,`Branch`=?,`Mail_ID`=?,`University`=?,`Mobile_No`=?,`Password`=? WHERE `Password`"+pass+"'";
                try{
                    ps=(PreparedStatement) MyConnection.getConnection().prepareStatement(query);
                    ps.setString(1, NAME);
                    ps.setString(2, roll);
                    ps.setString(3, Br);
                    ps.setString(4, Mail);
                    ps.setString(5, uni);
                    ps.setString(6, num);
                    ps.setString(7, RePwd);
                    
                     if(ps.executeUpdate()>0){
                            JOptionPane.showMessageDialog(this, "Password changes successfully.....");
                                new HomePage().setVisible(true);
                                this.setVisible(false);
                            jPasswordField1.setText("");
                            jPasswordField2.setText("");
                            jPasswordField3.setText("");
                     }
                   
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Error!"+e);
                    jPasswordField1.setText("");
                    jPasswordField2.setText("");
                    jPasswordField3.setText("");
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Your old Password is not matched...Please try again");
                jPasswordField1.setText("");
                jPasswordField2.setText("");
                jPasswordField3.setText("");
            }
           
        }else{
            JOptionPane.showMessageDialog(this, "New Password Does not match...");
            jPasswordField1.setText("");
            jPasswordField2.setText("");
            jPasswordField3.setText("");
        }
    }
        }
        }else{
            JOptionPane.showMessageDialog(this, "Password should be 6 character...");
            jPasswordField1.setText("");
            jPasswordField2.setText("");
            jPasswordField3.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(HomePage.count==1){
            new HomePage().setVisible(true);
            this.setVisible(false);
        }else{
            new Admin_Login().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    // End of variables declaration//GEN-END:variables
}
