/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package component.managment.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Hardik Bhadru
 */
public class Login extends javax.swing.JFrame {
    static int flag;
    static String No;
    private Connection cn;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setExtendedState(getExtendedState()|Login.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ICT Department");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(770, 60, 460, 70);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hardik Bhadru\\Documents\\NetBeansProjects\\Component Managment System\\mysql-connector-java-5.1.48\\marwadi-university.png")); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1420, 10, 500, 120);

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("ICT Student Login");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(180, 30, 410, 60);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enrollment No");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 170, 190, 28);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 300, 190, 28);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(50, 200, 290, 40);

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOG IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(50, 410, 120, 40);

        jPasswordField2.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jPanel2.add(jPasswordField2);
        jPasswordField2.setBounds(50, 330, 290, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(210, 220, 730, 640);

        jPanel3.setBackground(new java.awt.Color(51, 0, 102));
        jPanel3.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Other Branch Student");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(130, 20, 410, 60);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enrollment No");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(50, 170, 190, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 300, 190, 30);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(50, 200, 270, 40);

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOG IN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(50, 410, 120, 40);

        jButton3.setBackground(new java.awt.Color(102, 102, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("New Registration");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(270, 410, 210, 40);

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jPanel3.add(jPasswordField1);
        jPasswordField1.setBounds(50, 330, 270, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(1080, 220, 680, 640);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Created by:- Hardik Bhadru");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1610, 960, 300, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1930, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String pass = jPasswordField2.getText();
    String unm = jTextField2.getText();
    Login.No=unm;
    try{
        PreparedStatement ps=null;
        String query="select * from ict_student where Roll_No=? and Password=?";
        ps=MyConnection.getConnection().prepareStatement(query);
        ps.setString(1, jTextField2.getText());
        ps.setString(2, jPasswordField2.getText());
        ResultSet rs=ps.executeQuery();
        if(rs.next()){
                String nm=rs.getString("Name");
                String br=rs.getString("Branch");
                String ml=rs.getString("Mail_ID");
                String no=rs.getString("Mobile_number");
            if(unm.equals("Admin")){
                Change_Password x= new Change_Password();
                x.change(nm, unm,br,ml,no,pass);
                Admin_Login l=new Admin_Login();
                l.display4(nm,unm,ml);
                new Admin_Login().setVisible(true);
                this.setVisible(false);           
            }
            else{
                 HomePage d=new HomePage();
                 Issue_page d1=new Issue_page();
                 Return_Comp d2=new Return_Comp();
                 New_Component_Request l=new New_Component_Request();
                 Change_Password x= new Change_Password();
                 x.change(nm, unm,br,ml,no,pass);
                 d.display(nm,unm,br,ml);
                 d1.display2(nm);
                 d2.display3(nm,No);
                 l.disp(nm,unm, ml);
                 new HomePage().setVisible(true);
                 this.setVisible(false);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid Log in Id Password..!!!");
            jTextField2.setText("");
            jPasswordField2.setText("");
        }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String unm = jTextField1.getText();
        String pass=jPasswordField1.getText();
        String query="select * from non_ict_student_registartion where Roll_No=? and Password=?";
        try{
            PreparedStatement ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, jTextField1.getText());
            ps.setString(2, jPasswordField1.getText());
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                    String nm=rs.getString("Name");
                    String br=rs.getString("Branch");
                    String ml=rs.getString("Mail_ID");
                    String uni=rs.getString("University");
                    String no=rs.getString("Mobile_number");
                    HomePage d=new HomePage();
                    d.display(nm,unm,br,ml);
                    Issue_page d1=new Issue_page();
                    Return_Comp d2=new Return_Comp();
                    New_Component_Request l=new New_Component_Request();
                    Change_Password x= new Change_Password();
                    x.chan(uni);
                    x.change(nm,unm,br,ml,no,pass);
                    d1.display2(nm);
                    d2.display3(nm,No);
                    l.disp(nm,unm, ml);
                    JOptionPane.showMessageDialog(this, "You are successfully log in...!!!!");
                    new HomePage().setVisible(true);
                    this.setVisible(false);
                }
             else {
                JOptionPane.showMessageDialog(this, "Invalid Log in Id Password..!!!");
                jTextField1.setText("");
                jPasswordField1.setText("");
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Non_ICT_registration().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
