/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package component.managment.system;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hardik Bhadru
 */
public class Return_Comp extends javax.swing.JFrame {
    static String nm="",roll="";
    private Connection cn;
    static String quantity=null;
    private PreparedStatement ps=null;
    ResultSet rs;
    /**
     * Creates new form Return_Comp
     */
    public Return_Comp() {
        initComponents();
        display1();
        fetch();
        setExtendedState(getExtendedState()|Login.MAXIMIZED_BOTH);
    }
    void display3(String unm,String rol){
       Return_Comp.nm=unm;
       Return_Comp.roll=rol;
    }
    void display1(){
        jLabel5.setText(nm);
        jLabel4.setText(roll);
    }
    public void fetch(){
        try{
            String query="SELECT * FROM `component_issue`";
            java.sql.PreparedStatement ps=MyConnection.getConnection().prepareStatement(query);
            rs=ps.executeQuery(query);
            int count=0;
            while(rs.next())
            {
                String d = rs.getString("Roll_No");
                String e = rs.getString("Component_Name");
                String f = rs.getString("Quantity");
                String g = rs.getString("Date");
                if(d.equals(roll)){
                    count++;
                    String sr=Integer.toString(count);
                    DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
                    model.addRow(new Object[]{sr,d,e,f,g});
                }else{
                    continue;
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void del(){
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(120, 40, 630, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:-");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 40, 110, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enrollment No:-");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 110, 210, 36);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(230, 110, 380, 30);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No.", "Roll No.", "Component Name", "Quantity", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(40, 170, 670, 440);

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(40, 640, 120, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(120, 160, 760, 740);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 52)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Return Component");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(720, 30, 530, 60);

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Component Name:-");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(60, 70, 260, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("Quantity:-");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(60, 210, 150, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setText("Remarks:-");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(60, 470, 132, 40);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(60, 120, 380, 40);

        jTextField2.setBackground(new java.awt.Color(255, 255, 204));
        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jPanel3.add(jTextField2);
        jTextField2.setBounds(60, 260, 380, 40);

        jTextArea1.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(60, 520, 370, 90);

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Fully Damage");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(60, 330, 240, 45);

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Partially Damage");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(60, 370, 270, 45);

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Perfect");
        jPanel3.add(jRadioButton3);
        jRadioButton3.setBounds(60, 410, 230, 45);

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(90, 660, 110, 40);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(250, 660, 120, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(1010, 160, 760, 740);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Created by:- Hardik Bhadru");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1610, 960, 300, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1930, 1050);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new HomePage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
        int row = jTable1.getSelectedRow();
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        String cnm=model.getValueAt(row, 2).toString();
        String qu=model.getValueAt(row, 3).toString();
        jTextField1.setText(cnm);
        jTextField2.setText(qu); 
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please Select Row.!!!","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        int row=jTable1.getSelectedRow();
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        String selected=model.getValueAt(row, 4).toString();
        String oldq=model.getValueAt(row, 3).toString();
        String newq=jTextField2.getText();
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date=new Date();
        String dt=sdf.format(date);
        //String dt="06/04/2020 13:12:10";
        String cnm=jTextField1.getText();
        String qu=jTextField2.getText();
        String rm=jTextArea1.getText();
        jRadioButton1.setActionCommand("Fully Damage");
        jRadioButton2.setActionCommand("Partially Damage");
        jRadioButton3.setActionCommand("Perfect");
        String cond=buttonGroup1.getSelection().getActionCommand();
        if(Integer.parseInt(oldq)<Integer.parseInt(newq)){
            JOptionPane.showMessageDialog(this, "You enter wrong quantity value","Error",JOptionPane.ERROR_MESSAGE);
        }else{
                    try{
                        String query2="SELECT * FROM `avaliable_comp` WHERE `Component Name`=?";
                        try{
                            ps=(PreparedStatement)MyConnection.getConnection().prepareStatement(query2);  
                            ps.setString(1,cnm);
                            rs=ps.executeQuery();
                            if(rs.next()){
                                quantity=rs.getString("Quantity");
                            }
                        }catch(Exception ev ){
                            JOptionPane.showMessageDialog(this, ev);
                        }
                            String queryup="UPDATE `avaliable_comp` SET `Component Name`=?,`Quantity`=? WHERE `Component Name`='"+cnm+"'";
                            ps=null;
                            ps=(PreparedStatement)MyConnection.getConnection().prepareStatement(queryup);
                            ps.setString(1, cnm);
                            int co=(Integer.parseInt(qu))+(Integer.parseInt(quantity));
                            String upd=Integer.toString(co);
                            ps.setString(2, upd);
                            ps.executeUpdate();
                        }catch(Exception ew){
                            JOptionPane.showMessageDialog(this, ew);
                        }
                        if(Integer.parseInt(oldq)==Integer.parseInt(newq)){
                            String query="INSERT INTO `return history`(`Roll_No`, `Component_Name`, `Quantity`, `Condition`, `Remarks`, `Date`) VALUES (?,?,?,?,?,?)";
                            ps=(PreparedStatement) MyConnection.getConnection().prepareStatement(query);
                            ps.setString(1, roll);
                            ps.setString(2, cnm);
                            ps.setString(3, qu);
                            ps.setString(4, cond);
                            ps.setString(5, rm);
                            ps.setString(6, dt);
                            ps.addBatch();
                            ps.executeBatch();
                            ps=null;
                            ps = (PreparedStatement) MyConnection.getConnection().prepareStatement("DELETE FROM `component_issue` WHERE `Date`='"+selected+"' ");
                            ps.executeUpdate();
                            model.removeRow(row);
                            JOptionPane.showMessageDialog(this, "Data Updated","Information",JOptionPane.INFORMATION_MESSAGE);
                            jTextArea1.setText("");
                            jTextArea1.setText("");
                            jTextField2.setText("");
                        }else{
                            String queryu="UPDATE `component_issue` SET `Roll_No`=?,`Component_Name`=?,`Quantity`=?,`Date`=? WHERE `Date`='"+selected+"'";
                            ps=(PreparedStatement) MyConnection.getConnection().prepareStatement(queryu);
                            ps.setString(1, roll);
                            ps.setString(2, cnm);
                            ps.setString(3, qu);
                            ps.setString(4, selected);
                            ps.executeUpdate();
                            String query="INSERT INTO `return history`(`Roll_No`, `Component_Name`, `Quantity`, `Condition`, `Remarks`, `Date`) VALUES (?,?,?,?,?,?)";
                            ps=(PreparedStatement) MyConnection.getConnection().prepareStatement(query);
                            ps.setString(1, roll);
                            ps.setString(2, cnm);
                            ps.setString(3, qu);
                            ps.setString(4, cond);
                            ps.setString(5, rm);
                            ps.setString(6, dt);
                            ps.addBatch();
                            ps.executeBatch();
                            JOptionPane.showMessageDialog(this, "Data Updated...","Information",JOptionPane.INFORMATION_MESSAGE);
                            jTextArea1.setText("");
                            jTextArea1.setText("");
                            jTextField2.setText("");
                        }
                    del();
                    fetch();
                }
        }catch(Exception e){
                    JOptionPane.showMessageDialog(this,"Please Enter all Values","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return_Comp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return_Comp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return_Comp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return_Comp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return_Comp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
